---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1  # Only one replica for single-node cluster
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch-container
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0  # Docker image name
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"  # Java memory settings
        - name: ELASTIC_PASSWORD
          value: "elastic"  # Elasticsearch password
        ports:
        - containerPort: 9200  # Default Elasticsearch port
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data  # Mount path for data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config  # Reference to ConfigMap
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-pvc  # Reference to PVC for data storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust storage size as needed

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch
