apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user root;
    worker_processes auto;
    pid /var/run/nginx.pid;
    error_log /var/log/nginx/error.log warn;
    events {
        worker_connections 2048;
    }

    http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format custom escape=json
        '{'
        '"time_local":"$time_local",'
        '"remote_addr":"$remote_addr",'
        '"request":"$request",'
        '"request_length":"$request_length",'
        '"upstream_response_time":"$upstream_response_time",'
        '"status": "$status",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"request_time":"$request_time",'
        '"http_referrer":"$http_referer",'
        '"http_user_agent":"$http_user_agent"'
        '}';
        access_log /var/log/nginx/access.log custom;
        error_log /var/log/nginx/error.log;

        gzip on;
        gzip_disable "msie6";

        server {
            listen 80;

            location / {
                proxy_pass  http://empms-frontend:3000/;
            }

            location /healthz {
                access_log off;
                return 200;
            }
        }
    }
